# Generated by Django 5.2.17 on 2026-08-31 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="receipts/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting to be read"),
                            ("parsed", "Read"),
                            ("imported", "Check created"),
                            ("failed", "Could not be read"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "parsed_data",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                ("error", models.TextField(blank=True, editable=False)),
                (
                    "model_used",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parsed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploads",
                        to="checks.check",
                        verbose_name="check",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Everyone here is put on every parsed item. Leave empty to split later.",
                        related_name="receipt_uploads",
                        to="checks.participant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipt_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "receipt upload",
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
    ]
